school/classroom/urls.py
from django.urls import path
from . import views

app_name = 'classroom'

# /classroom/
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('thank_you/', views.ThankYouView.as_view(), name='thank_you'),
    path('contact/', views.ContactFormView.as_view(), name='contact'),
    path('teacher_create/', views.TeacherCreateView.as_view(), name='teacher_create'),
    path('teacher_list/', views.TeacherListView.as_view(), name='teacher_list'),
    path('teacher_detail/<int:pk>/', views.TeacherDetailView.as_view(), name='teacher_detail'),
    path('teacher_update/<int:pk>/', views.TeacherUpdateView.as_view(), name='teacher_update'),
    path('teacher_delete/<int:pk>/', views.TeacherDeleteView.as_view(), name='teacher_delete'),
    ]

school/school/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('classroom/', include('classroom.urls')),
]

school/classroom/models.py
from django.db import models

# Create your models here.
class Teacher(models.Model):
    objects = models.Manager() # this is needed to avoid VS Code error
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    subject = models.CharField(max_length=20)
    
    def __str__(self):
        return f"{self.first_name}, {self.last_name}, {self.subject}"
     

school/classroom/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField()
    message = forms.CharField(widget=forms.Textarea)
        

school/classroom/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import TemplateView, FormView, CreateView, ListView, DetailView, UpdateView, DeleteView

from . import forms
from . import models

# Create your views here.
class HomeView(TemplateView):
    template_name = 'classroom/home.html'
    
class ThankYouView(TemplateView):
    template_name = 'classroom/thank_you.html'
    
class TeacherCreateView(CreateView):
    model = models.Teacher
    fields = "__all__"
    success_url = reverse_lazy('classroom:thank_you')
    
class TeacherListView(ListView):
    model = models.Teacher
    # customize the query here:
    # queryset = models.Teacher.objects.all()
    queryset = models.Teacher.objects.order_by('first_name')
    context_object_name = 'teachers_list'
    
class TeacherDetailView(DetailView):
    model = models.Teacher
    
class TeacherUpdateView(UpdateView):
    model = models.Teacher
    # fields = "__all__"
    fields = ["subject"]
    success_url = reverse_lazy('classroom:teacher_list')
    
class TeacherDeleteView(DeleteView):
    model = models.Teacher
    success_url = reverse_lazy('classroom:teacher_list')
    
# this is the "old" way of creating a form without using TemplateViewModel       
class ContactFormView(FormView):
    form_class = forms.ContactForm
    template_name = 'classroom/contact.html'
    
    # what to do if the form is submitted and valid
    success_url = reverse_lazy('classroom:thank_you')
  
    def form_valid(self, form):
        print(form.cleaned_data)
        return super().form_valid(form)
        

school/classroom/templates/classroom/contact.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
    <h1>Form Validation</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit", value="Submit">
    </form>

</body>
</html>

school/classroom/templates/classroom/home.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>welcome to homepage</h1>
    <ul>
        <li>
            <a href="{% url 'classroom:thank_you' %}">Thank You</a>
        </li>
        <li>
            <a href="{% url 'classroom:contact' %}">Contact</a>
        </li>
        <li>
            <a href="{% url 'classroom:teacher_create' %}">Create a teacher</a>
        </li>
        <li>
            <a href="{% url 'classroom:teacher_list' %}">View all teachers</a>
        </li>
    </ul>
</body>
</html>

school/classroom/templates/classroom/teacher_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Are you sure you want to delete this teacher?</h1>
    <h3>{{ teacher }}</h3>

    <form action="" method="post">
        {% csrf_token %}
        <input type="submit" value="Delete">
    </form>
    
</body>
</html>

school/classroom/templates/classroom/teacher_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
   
    <h1>Teacher Detail</h1>
    {{ teacher }}

</body>
</html>

school/classroom/templates/classroom/teacher_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Teacher Form</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit", value="Submit">
    </form>
</body>
</html>

school/classroom/templates/classroom/teacher_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>List of Teachers</h1>
    <ul>
        {% for teacher in teachers_list %}
            <li>
                <h4>
                    <a href="/classroom/teacher_detail/{{ teacher.id }}">{{ teacher.first_name | title }} {{ teacher.last_name | title }}, {{ teacher.subject | title }}</a>
                </h4>
                <a href="/classroom/teacher_update/{{ teacher.id }}">Update subject</a>
                <a href="/classroom/teacher_delete/{{ teacher.id }}">Delete</a>
            </li>
        {% endfor %}
    </ul>
</body>
</html>

school/classroom/templates/classroom/thank_you.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Thank you</h1>
</body>
</html>