pj_one/app_one/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.simple_view),
    path('<int:num1>/<int:num2>',views.add_view),
    path('<int:page_number>',views.page_num_view),
    path('<str:topic>/',views.news_view,name='topic-page'),
]

pj_one/first_app/urls.py
from django.urls import path
from . import views

# assign the app namespace
app_name = 'first_app'

urlpatterns = [
    path('', views.main_view, name='app_home'),
    path('variables/', views.variables_view, name='variables'),
    path('get_all/', views.get_all, name='get_all'),
    path('<int:page_number>', views.page_num_view, name='redirect'),
    path('<str:topic>/', views.news_view, name='topic-page'),
]

pj_one/pj_one/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index_view),
    path('admin/', admin.site.urls),
    path('first_app/',include('first_app.urls'))
]

pj_one/first_app/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator

# Create your models here.
class MyModel(models.Model):
    objects = models.Manager() # this is needed to avoid VS Code error
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    age = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(120)])
    rate = models.IntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(5)])
        
    def __str__(self):
        return self.first_name + ' ' + self.last_name
    

pj_one/app_one/views.py
from django.http.response import HttpResponseNotFound, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponse

# Create your views here.

# ROUTES AND URLs LECTURE



# # BASIC FUNCTION VIEWS LECTURE
def simple_view(request):
    return HttpResponse('SIMPLE VIEW!')
    # return render(request,'first_app/example.html')


# DYNAMIC VIEWS AND VIEW LOGIC LECTURE

def add_view(request,num1,num2):
    result = num1+num2
    return HttpResponse(str(result))


articles = {
    "sports":"Welcome to the sports page",
    "finance":"Finance news here",
    "politics":"Politics is in the news"
}


# def news_view(request,topic):
#     headline = f"<h1>{articles[topic]}</h1>"
#     return HttpResponse(headline)

# REDIRECTS AND 404s LECTURE


def news_view(request,topic):
    try:
        headline = f"<h1>{articles[topic]}</h1>"
        return HttpResponse(headline)
    except:
        headline = "<h1>No article page for that topic!</h1>"
        return HttpResponseNotFound(headline)


pages = ['sports','finance','politics']
# REDIRECTS
def page_num_view(request,page_number):
    # domain.com/first_app/1 ----> domain.com/first_app/finance
    topic = pages[page_number]
    return HttpResponseRedirect(topic)

def num_page_view(request,num_page):

    topics_list = list(articles.keys()) # ['sports','finance','politics']
    topic = topics_list[num_page]

    
    return HttpResponseRedirect(reverse('topic-page',args=[topic]))

pj_one/first_app/views.py
from django.http.response import HttpResponseNotFound, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponse
from . import models

# /first_app/

# sections

articles = {
    "sports":"Welcome to the sports page",
    "finance":"Finance news here",
    "politics":"Politics is in the news"
}

# function views

# /
def main_view(request):
    return render(request,'first_app/home_app.html')

# /get_all
def get_all(request):
    
    all_users = models.MyModel.objects.all()
    context = {'users':all_users}
    
    return render(request, 'first_app/get_all.html', context=context)

# /variables/
def variables_view(request):
    
    my_var = {'first_name':'John','last_name':'Doe', 'a_list':["dog","cat","mouse"], 'a_dict':{'a':1,'b':2,'c':3}, 'user_auth':True}
    
    return render(request,'first_app/variables.html', context=my_var)

# redirects

def news_view(request,topic):
    try:
        headline = f"<h1>{articles[topic]}</h1>"
        return HttpResponse(headline)
    except:
        headline = "<h1>No article page for that topic!</h1>"
        return HttpResponseNotFound(headline)

pages = ['sports','finance','politics']

def page_num_view(request,page_number):
    topic = pages[page_number]
    return HttpResponseRedirect(topic)

def num_page_view(request,num_page):

    topics_list = list(articles.keys())
    topic = topics_list[num_page]
    
    return HttpResponseRedirect(reverse('topic-page',args=[topic]))

pj_one/pj_one/views.py
from django.http import HttpResponse
from django.shortcuts import render


# probably would make sense to link this to a template within an home_page_app
def index_view(request):
    return render(request, 'base_template.html')

pj_one/first_app/templates/first_app/get_all.html
{% extends 'base_template.html' %}
{% load static %}

{% block title %} <title>All Users</title> {% endblock %}

    {% block content %}
    <div class="container">
        <h2>Here's all the user list</h2>
        <ul>
            {% for user in users %}
                <li>{{ user }}</li>
            {% endfor %}
        </ul>
    </div>
    {% endblock %}

pj_one/first_app/templates/first_app/home_app.html
{% extends 'base_template.html' %}
{% load static %}

{% block title %} <title>App Page</title> {% endblock %}

    {% block content %}
    <div class="container">
        <h1 class="display-1">this is the home page</h1>
        <h3><a href="{% url 'first_app:variables' %}">Go to Variables page</a></h3>
        <img src="{% static 'first_app/img/sample-image.jpg' %}" alt="home_app" class="img-fluid">
    </div>
    {% endblock %}

pj_one/first_app/templates/first_app/home_app_bk.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>home app</title>

    <!-- CSS  -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    
</head>
<body>
    <div class="container">
        <h1 class="display-1">this is the home page</h1>
        <h3><a href="{% url 'first_app:variables' %}">Go to Variables page</a></h3>
    </div>

</body>
</html>

pj_one/first_app/templates/first_app/variables.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Variables</title>

    <!-- CSS  -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

</head>
<body>
    <div class="container">
        <h1>hello variables</h1>

        <h2>First name is {{ first_name | capfirst }} and last name is {{ last_name | length }} char long</h2>
        <h3>{{ a_list.0 }}</h3>
        <h3>{{ a_dict.b }}</h3>
        <h3>{# this is a comment #}</h3>
        
        <ul>
            {% for item in a_list %}
                
                {% if item == "dog" %}
                    <li>{{ item }}</li>
                {% else %}
                    <li>{{ item }} it's not a dog</li>
                {% endif %}
            
            {% endfor %}
        </ul>    

        {% if user_auth == True %}
            <p>{{ "Welcome to our page" }}</p>
        {% elif user_auth == False %}
            <p>{{ "User must log in" }}</p>
        {% else %}
            <p>{{ "User error" }}</p>
        {% endif %}


    </div>    

</body>
</html>

pj_one/templates/base_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    {% load static %}

    {% block title%}
    <title>Home Page</title>
    {% endblock %}

    <!-- FAVICON -->
    <link rel="icon" href="{% static 'first_app/img/favicon.jpg' %}">

    <!-- CSS  -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

</head>
<body>
    
    <!-- Above the block -->
    {% block content %}
        <div class="container">
            <h1>this is the home page</h1>
            <h3><a href="{% url 'first_app:app_home' %}">Go to App home page</a></h3>
        </div>
    {% endblock %}
    <!-- Below the block -->

</body>
</html>