pj_car/cars/urls.py
from django.urls import path
from . import views

app_name = 'cars'

urlpatterns = [
    path('show/', views.show, name='show'),
    path('add/', views.add, name='add'),
    path('delete/', views.delete, name='delete'),
]

pj_car/pj_car/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('cars/', include('cars.urls')),
    path('admin/', admin.site.urls),
]

pj_car/cars/models.py
from django.db import models

# Create your models here.
class Car(models.Model):
    objects = models.Manager() # this is needed to avoid VS Code error
    brand = models.CharField(max_length=30)
    year = models.IntegerField()
    
    def __str__(self):
        return f'This is a {self.brand} from {self.year}'
      

pj_car/cars/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from . import models

# Create your views here.
# /cars/

def show(request):
    all_cars = models.Car.objects.all()
    context = {'all_cars': all_cars}
    
    return render(request, 'cars/html/show.html', context=context)

def add(request):
    if request.POST:
        brand = request.POST["brand"]
        year = int(request.POST["year"])
        models.Car.objects.create(brand=brand, year=year)
        return redirect(reverse('cars:show'))
    else:
        return render(request, 'cars/html/add.html')

def delete(request):
    if request.POST:
        pk = request.POST["pk"]
        try:
            models.Car.objects.get(pk=pk).delete()
            return redirect(reverse('cars:show'))
        except:
            print("pk not found")
            return redirect(reverse('cars:show'))
    else:
        return render(request, 'cars/html/delete.html')

pj_car/cars/templates/cars/html/add.html
{% extends 'html/base.html' %}
{% load static %}

{% block title %} <title>Add</title> {% endblock %}

{% block content %}
<div class="container">
    <h1>add.html</h1>
    <h2>Add a new car to the db</h2>
    <form action="" method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label for="brand">Brand</label>
            <input class="form-control" type="text" id="brand", name="brand">
        </div>
        <div class="form-group">
            <label for="year">Year</label>
            <input class="form-control" type="text", id="year", name="year">
        </div><br>
        <input class="btn btn-primary" type="submit">
    </form>
</div>


{% endblock %}

pj_car/cars/templates/cars/html/delete.html
{% extends 'html/base.html' %}
{% load static %}

{% block title %} <title>Delete</title> {% endblock %}

{% block content %}
<div class="container">
    <h1>delete.html</h1>
    <h2>delete a car from the db</h2>
    <form action="" method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label for="pk">Primary Key</label>
            <input class="pk" type="text" id="pk", name="pk">
        </div><br>
        <input class="btn btn-primary" type="submit">
    </form>
</div>

{% endblock %}

pj_car/cars/templates/cars/html/show.html
{% extends 'html/base.html' %}
{% load static %}

{% block title %} <title>Show</title> {% endblock %}

{% block content %}
<div class="container">
    <h1>show.html</h1>
        <ul>
            {% for car in all_cars %}
            <li>{{ car }}</li>
            {% endfor %}
        </ul>
</div>
{% endblock %}

pj_car/templates/html/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    {% load static %}

    {% block title%}
    <title>Home Page</title>
    {% endblock %}

    <!--BOOTSTRAP CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

</head>
<body>

    <!-- BOOTSTRAP NAVBAR -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'cars:show' %}">SHOW</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'cars:add' %}">ADD</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'cars:delete' %}">DELETE</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>

    {% block content %}
    {% endblock %}
    
</body>
</html>